# Generated by Django 4.0.1 on 2022-01-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_data',
            new_name='booking_date',
        ),
    ]
